//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_API.CRMService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRMService.ICRM")]
    public interface ICRM {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRM/GetLookups", ReplyAction="http://tempuri.org/ICRM/GetLookupsResponse")]
        System.Data.DataSet GetLookups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRM/GetLookups", ReplyAction="http://tempuri.org/ICRM/GetLookupsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLookupsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRMChannel : CRM_API.CRMService.ICRM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRMClient : System.ServiceModel.ClientBase<CRM_API.CRMService.ICRM>, CRM_API.CRMService.ICRM {
        
        public CRMClient() {
        }
        
        public CRMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetLookups() {
            return base.Channel.GetLookups();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLookupsAsync() {
            return base.Channel.GetLookupsAsync();
        }
    }
}
